spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: nikozohrabyan@mail.ru
    password: Ni1ko2lya34
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jackson:
    serialization:
      fail-on-empty-beans:  false

server:
  port: 8081

file:
  upload:
    dir: D:\IdeaProjects\2021-spring\HairSalon\upload




